# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "52ac45e79067ae5ad62a3cfdbd632e23"
name = "int-quoter-pub"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
