# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "27c346eab6ca30969869df69f6c39a59"
name = "int-quoter-pub"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
